name: hybrid_4
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  http: ^0.13.4

dev_dependencies:
  lints: ^2.0.0

executables:
  main:
    script: bin/main.dart
